- name: Create the Alertmanager Job Template
  ansible.controller.job_template:
    name: Demo EDA Alertmanager handler
    job_type: "run"
    organization: "Default"
    inventory: "{{ aap2_controller_snow_inventory }}"
    playbook: playbooks/alert-handler.yml
    state: "present"
    project: "{{ aap2_controller_project }}"
    credentials:
    - "{{ aap2_controller_snow_credential }}"
    ask_variables_on_launch: true
    controller_host: "{{ aap2_controller_url }}"
    controller_username: "{{ aap2_controller_username }}"
    controller_password: "{{ aap2_controller_password }}"
    validate_certs: "{{ aap2_controller_validate_certs }}"
